javac -d . Omby.java
javac -d . Olona.java
javac -d . Connect.java
javac -d . LocalStorage.java
javac -d . Transaction.java
javac -d . LogIn.java
javac -d . OmbyCon.java
javac -d . OlonaCon.java
javac -d . PageConfirmAchat.java
javac -d . PageAccueil.java
javac -d . PageLogIn.java
javac -d . PageAchat.java
javac -d . Fenetre.java
javac -d . App.java